version: '3.8'
services:
  gateway:
    build: gateway/
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - HOST=shareit-server
      - PORT=9090
    depends_on:
      - server

  server:
    build: server/
    container_name: shareit-server
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=shareit_db
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: shareit-db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shareit_db